.gitignore:
    paths:
        - "/test/integration/**/.librarian"
        - "/test/integration/**/.tmp"
        - ".kitchen"
        - ".vscode"
Gemfile:
    required:
        ":development":
            - gem: "kitchen-docker"
              version: "2.9.0"
            - gem: "kitchen-puppet"
              version: "3.5.1"
            - gem: "serverspec"
              version: "2.41.5"
            - gem: "test-kitchen"
              version: "2.2.5"
Rakefile:
    requires:
        - "kitchen/rake_tasks"
    extras:
        - "Kitchen::RakeTasks.new"
        - |
            task :integration_test do
              [:metadata_lint, :lint, :validate, :spec].each do |test|
                Rake::Task[test].invoke
              end
              Rake::Task['kitchen:all'].invoke
            end
.travis.yml:
    includes:
        - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=integration_test
          rvm: 2.5.3
          stage: spec
          script: 'travis_wait 80 bundle exec rake $CHECK'
    global_env:
        - "GITHUB_USE_AUTH=true"
        - "GITHUB_USE_OAUTH=true"
        - "GITHUB_USERNAME=37927623628d59a25857"
        - 'secure: "Jb7lfi2Zrm01eP3JzH/WsgqZMVZ4K1hk6zr02BqKYBqsQj1KEiiiptaQl5nNmPLJXasJG5udf7mFj1FC51ds7YSyXfBaGsAp5Jf4ZCl48zZqzScnSjYdDKLlnnKmKBrM4Jr5cuZRRmmmA1uUtzCQFJGO+UXUCoDi2rv8Lg32DrMqbeVdPiFlbxax5Qi62AlQaQzkzP2EmQ82/IuXPrioo2DjG0Fqdg2jDL3SSourjRvBhfF/3xvT696Ur6ErQsKNayTYt+cH2SfJKwd+hQPTjcvRt4a4iohxQup1CdLcimKl9sdVtCQz/rTyZ86bStV/+wJz40fo0aM2PublZIJcvdAzTdZmYCuWbMxKew5NiSNQ8Ein/clEV0bUAk6v63B50B9VWXpdJ6F7M62hasY4/c3PxLfIyQ+LeHOnMifo8duqNCnz0E4YG0ELergG3EkKEI2g/FHF3e1nACVvdRkEynowG0AGrs/+90cOFQeYp0pMJ9ZJpMm9Kers+2fcyLsMKd6INNbiT0NXuyfIFe1lGIIX+s2QKA6hc4jZRNwlNmyk2v2mKEPpKuX01aF5PH84oQfK7pvda9OzaeFsCsh/7eF21bU3jRzXo2tPNnt4neqdvlaV4epd0nL8GaS2NeGCAJ4PyVPPh6dG8EYaauqgzIgb+g6PM7a5xTJTzXJr3TI="'
    user: "dodevops"
    secure: "Fe3Kpkeug1259eW0XvGEqC6wtW80Z6cIwiz15ESA0UMIbzn4nQNfdJmT2YFTqz/mNGshpNLGHO6xim9mH/Wle/U7Cu9UD1MmsDgKT8E9+0/zynW+QOq0jINnRLbvAb/85BBX1kh/jg8FRihCfLDmFL23KXyAyzycgqRCf40TN96Nn2kNk/KW3xxm5H1Fhix37pbKVIaMSAaDPuE+8FfcZjnSXWBNBB1Ms6VF4wwsQtqum6n/dlgMEDTg1D/vnxgv5+kfMCYWPCaodrf9kYhDBRaxtRPbs8TQG99/RWc5v5lKByeBvHTMHAaxOESzh7TOWrvnDGW7lP0KEPqZLZvkT7yC+fhtFT3js/6QhdIud5UsCbok0OgcKV9uK8z9NTSw6Ge3OMaCod1RuzCsw8WyPf2X5j/gXRz/50SrqarL3rdfX1k1WIM3qBY9ScXz0cBk19dLcgkhosAH9bLmM0qHvvXJetbCAuzle9h1mPA6b6VAMT9gZT0AQOcZfmmPnrk9HvOGBbKG5JvA3ZiOBObz21CBoD8rGklgBn7RYRY7pd/JC5Zag09MTvw6dOCXSQRs6B1jDQI31HM9jXf4oB/qvC8Jl2Q8opzuEgfGhtu0IPczllAT0QmyA217Mqjk8UuEGgoUHstuab/a36FOyeBvVXHBI6e8HKQwvzZJz7Q642U="
